# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Settings_Ui(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(640, 139)
        self.horizontalLayoutWidget = QtWidgets.QWidget(main)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 601, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_button.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.formLayoutWidget = QtWidgets.QWidget(main)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setAcceptDrops(False)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.api_key = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.api_key.setObjectName("api_key")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.api_key)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Settings"))
        self.save_button.setText(_translate("main", "Save"))
        self.cancel_button.setText(_translate("main", "Cancel"))
        self.label.setText(_translate("main", "Notion API Key"))
